version: '2'
services: 
  mysql: 
    image: mysql:5.6.27
    environment:
      MYSQL_ROOT_USERNAME: "root"
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "db"
    ports:
      - "3306:3306"
